spring:
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  springdoc:
    api-docs:
      path=/api-docs:
logging:
  level:
    web: TRACE
    org:
      springframework:
        web: TRACE